services:
  mc-rtc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mc-rtc:latest
    container_name: mc-rtc-container
    volumes:
      - ..:/workspace/mc_rtc
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0}
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    stdin_open: true
    tty: true
